package dk.cocode.parvaz.ui.settings

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.text.KeyboardOptions
import dk.cocode.parvaz.R
import dk.cocode.parvaz.settings.Access
import dk.cocode.parvaz.settings.AccessParseException
import dk.cocode.parvaz.ui.theme.Ink
import dk.cocode.parvaz.ui.theme.InkSoft
import dk.cocode.parvaz.ui.theme.Olive
import dk.cocode.parvaz.ui.theme.Oxblood
import dk.cocode.parvaz.ui.theme.Paper

/**
 * Inline `parvaz://` editor. Live-only — the field is pre-filled with a
 * lossy reconstruction of the saved Access (deployment-id + redacted key)
 * so the user knows what's there, but the actual access key is not
 * surfaced in plaintext.
 *
 * Intentionally **does not touch the CA store**: the on-device root
 * generated by parvazd is tied to the device, not the relay deployment.
 * Pointing at a different Apps Script deployment doesn't invalidate the
 * existing trust chain.
 *
 * Reuses [Access.parse] so the URL grammar is identical to the
 * onboarding Import screen.
 *
 * The "saved" feedback is local-only state — caller is expected to
 * persist via [onSave] before this appears.
 */
@Composable
fun UrlEditSection(
    currentAccess: Access?,
    onSave: (Access) -> Unit,
) {
    val placeholder = remember(currentAccess) { currentAccess?.let(::redact).orEmpty() }
    // Plain `remember` (not `rememberSaveable`): a half-typed
    // parvaz://… URL contains the same access key we deliberately
    // store in EncryptedSharedPreferences. Persisting it into the
    // savedInstanceState bundle (which Android can spill to disk on
    // process death) would leak that key to plaintext storage.
    // Trade-off: input is lost across rotation — onboarding's
    // ImportAccessScreen accepts the same trade-off.
    var input by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }
    var savedFlash by remember { mutableStateOf(false) }

    LaunchedEffect(savedFlash) {
        if (savedFlash) {
            kotlinx.coroutines.delay(1500)
            savedFlash = false
        }
    }

    Text(
        text = stringResource(R.string.settings_url_section_label),
        style = MaterialTheme.typography.titleMedium,
        color = InkSoft,
    )

    OutlinedTextField(
        value = input,
        onValueChange = {
            input = it
            error = null
            savedFlash = false
        },
        placeholder = { Text(placeholder.ifEmpty { stringResource(R.string.settings_url_input_hint) }) },
        singleLine = true,
        keyboardOptions = KeyboardOptions(
            keyboardType = KeyboardType.Uri,
            imeAction = ImeAction.Done,
        ),
        isError = error != null,
        modifier = Modifier
            .fillMaxWidth()
            .testTag(SettingsTestTags.UrlField),
    )

    error?.let {
        Text(
            text = it,
            style = MaterialTheme.typography.bodySmall,
            color = Oxblood,
            modifier = Modifier.testTag(SettingsTestTags.UrlError),
        )
    }

    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically,
    ) {
        if (savedFlash) {
            Text(
                text = stringResource(R.string.settings_url_saved_label),
                style = MaterialTheme.typography.bodyMedium,
                color = Olive,
            )
        } else {
            Text("", style = MaterialTheme.typography.bodyMedium)
        }
        Button(
            onClick = {
                val raw = input.trim()
                if (raw.isEmpty()) return@Button
                try {
                    val parsed = Access.parse(raw)
                    onSave(parsed)
                    input = ""
                    error = null
                    savedFlash = true
                } catch (e: AccessParseException) {
                    error = e.message
                }
            },
            enabled = input.isNotBlank(),
            colors = ButtonDefaults.buttonColors(containerColor = Ink, contentColor = Paper),
            shape = RoundedCornerShape(2.dp),
            modifier = Modifier.testTag(SettingsTestTags.UrlSaveButton),
        ) {
            Text(stringResource(R.string.settings_url_save_cta))
        }
    }
}

private fun redact(access: Access): String {
    val tail = access.accessKey.takeLast(4)
    return "parvaz://${access.deploymentId}/••••$tail"
}
